nice ./new_starfitter 3 mirror_geometry.dat results/md_m25.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 7 mirror_geometry.dat results/md_m25.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 11 mirror_geometry.dat results/md_m25.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 15 mirror_geometry.dat results/md_m25.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 3 mirror_geometry.dat results/md_m26.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 7 mirror_geometry.dat results/md_m26.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 11 mirror_geometry.dat results/md_m26.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 15 mirror_geometry.dat results/md_m26.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 3 mirror_geometry.dat results/md_m27.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 7 mirror_geometry.dat results/md_m27.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 11 mirror_geometry.dat results/md_m27.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 15 mirror_geometry.dat results/md_m27.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 3 mirror_geometry.dat results/md_m28.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 7 mirror_geometry.dat results/md_m28.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 11 mirror_geometry.dat results/md_m28.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 15 mirror_geometry.dat results/md_m28.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 3 mirror_geometry.dat results/br_TAx4_m1.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 7 mirror_geometry.dat results/br_TAx4_m1.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 11 mirror_geometry.dat results/br_TAx4_m1.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 15 mirror_geometry.dat results/br_TAx4_m1.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 3 mirror_geometry.dat results/br_TAx4_m2.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 7 mirror_geometry.dat results/br_TAx4_m2.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 11 mirror_geometry.dat results/br_TAx4_m2.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 15 mirror_geometry.dat results/br_TAx4_m2.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 3 mirror_geometry.dat results/br_TAx4_m3.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 7 mirror_geometry.dat results/br_TAx4_m3.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 11 mirror_geometry.dat results/br_TAx4_m3.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 15 mirror_geometry.dat results/br_TAx4_m3.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 3 mirror_geometry.dat results/br_TAx4_m4.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 7 mirror_geometry.dat results/br_TAx4_m4.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 11 mirror_geometry.dat results/br_TAx4_m4.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 15 mirror_geometry.dat results/br_TAx4_m4.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 3 mirror_geometry.dat results/br_TAx4_m5.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 7 mirror_geometry.dat results/br_TAx4_m5.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 11 mirror_geometry.dat results/br_TAx4_m5.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 15 mirror_geometry.dat results/br_TAx4_m5.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 3 mirror_geometry.dat results/br_TAx4_m6.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 7 mirror_geometry.dat results/br_TAx4_m6.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 11 mirror_geometry.dat results/br_TAx4_m6.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 15 mirror_geometry.dat results/br_TAx4_m6.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 3 mirror_geometry.dat results/br_TAx4_m7.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 7 mirror_geometry.dat results/br_TAx4_m7.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 11 mirror_geometry.dat results/br_TAx4_m7.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 15 mirror_geometry.dat results/br_TAx4_m7.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 3 mirror_geometry.dat results/br_TAx4_m8.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 7 mirror_geometry.dat results/br_TAx4_m8.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 11 mirror_geometry.dat results/br_TAx4_m8.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
nice ./new_starfitter 15 mirror_geometry.dat results/br_TAx4_m8.stars.txt 1>> mirror_geometry.nparm.dat 2>> rejects.err
