rm -f star_report.dat
./new_star_report 0 mirror_geometry.tokuno results/br_m00.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/br_m01.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/br_m02.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/br_m03.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/br_m04.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/br_m05.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/br_m06.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/br_m07.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/br_m08.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/br_m09.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/br_m10.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/br_m11.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/lr_m00.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/lr_m01.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/lr_m02.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/lr_m03.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/lr_m04.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/lr_m05.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/lr_m06.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/lr_m07.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/lr_m08.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/lr_m09.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/lr_m10.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/lr_m11.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m01.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m02.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m03.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m04.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m05.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m06.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m07.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m08.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m09.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m10.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m11.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m12.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m13.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m14.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m15.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m16.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m17.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m18.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m19.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m20.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m21.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m22.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m23.stars.txt
./new_star_report 0 mirror_geometry.tokuno results/md_m24.stars.txt
./new_star_report 2 mirror_geometry.2parm results/br_m00.stars.txt
./new_star_report 2 mirror_geometry.2parm results/br_m01.stars.txt
./new_star_report 2 mirror_geometry.2parm results/br_m02.stars.txt
./new_star_report 2 mirror_geometry.2parm results/br_m03.stars.txt
./new_star_report 2 mirror_geometry.2parm results/br_m04.stars.txt
./new_star_report 2 mirror_geometry.2parm results/br_m05.stars.txt
./new_star_report 2 mirror_geometry.2parm results/br_m06.stars.txt
./new_star_report 2 mirror_geometry.2parm results/br_m07.stars.txt
./new_star_report 2 mirror_geometry.2parm results/br_m08.stars.txt
./new_star_report 2 mirror_geometry.2parm results/br_m09.stars.txt
./new_star_report 2 mirror_geometry.2parm results/br_m10.stars.txt
./new_star_report 2 mirror_geometry.2parm results/br_m11.stars.txt
./new_star_report 2 mirror_geometry.2parm results/lr_m00.stars.txt
./new_star_report 2 mirror_geometry.2parm results/lr_m01.stars.txt
./new_star_report 2 mirror_geometry.2parm results/lr_m02.stars.txt
./new_star_report 2 mirror_geometry.2parm results/lr_m03.stars.txt
./new_star_report 2 mirror_geometry.2parm results/lr_m04.stars.txt
./new_star_report 2 mirror_geometry.2parm results/lr_m05.stars.txt
./new_star_report 2 mirror_geometry.2parm results/lr_m06.stars.txt
./new_star_report 2 mirror_geometry.2parm results/lr_m07.stars.txt
./new_star_report 2 mirror_geometry.2parm results/lr_m08.stars.txt
./new_star_report 2 mirror_geometry.2parm results/lr_m09.stars.txt
./new_star_report 2 mirror_geometry.2parm results/lr_m10.stars.txt
./new_star_report 2 mirror_geometry.2parm results/lr_m11.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m01.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m02.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m03.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m04.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m05.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m06.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m07.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m08.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m09.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m10.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m11.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m12.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m13.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m14.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m15.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m16.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m17.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m18.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m19.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m20.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m21.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m22.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m23.stars.txt
./new_star_report 2 mirror_geometry.2parm results/md_m24.stars.txt
./new_star_report 3 mirror_geometry.3parm results/br_m00.stars.txt
./new_star_report 3 mirror_geometry.3parm results/br_m01.stars.txt
./new_star_report 3 mirror_geometry.3parm results/br_m02.stars.txt
./new_star_report 3 mirror_geometry.3parm results/br_m03.stars.txt
./new_star_report 3 mirror_geometry.3parm results/br_m04.stars.txt
./new_star_report 3 mirror_geometry.3parm results/br_m05.stars.txt
./new_star_report 3 mirror_geometry.3parm results/br_m06.stars.txt
./new_star_report 3 mirror_geometry.3parm results/br_m07.stars.txt
./new_star_report 3 mirror_geometry.3parm results/br_m08.stars.txt
./new_star_report 3 mirror_geometry.3parm results/br_m09.stars.txt
./new_star_report 3 mirror_geometry.3parm results/br_m10.stars.txt
./new_star_report 3 mirror_geometry.3parm results/br_m11.stars.txt
./new_star_report 3 mirror_geometry.3parm results/lr_m00.stars.txt
./new_star_report 3 mirror_geometry.3parm results/lr_m01.stars.txt
./new_star_report 3 mirror_geometry.3parm results/lr_m02.stars.txt
./new_star_report 3 mirror_geometry.3parm results/lr_m03.stars.txt
./new_star_report 3 mirror_geometry.3parm results/lr_m04.stars.txt
./new_star_report 3 mirror_geometry.3parm results/lr_m05.stars.txt
./new_star_report 3 mirror_geometry.3parm results/lr_m06.stars.txt
./new_star_report 3 mirror_geometry.3parm results/lr_m07.stars.txt
./new_star_report 3 mirror_geometry.3parm results/lr_m08.stars.txt
./new_star_report 3 mirror_geometry.3parm results/lr_m09.stars.txt
./new_star_report 3 mirror_geometry.3parm results/lr_m10.stars.txt
./new_star_report 3 mirror_geometry.3parm results/lr_m11.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m01.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m02.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m03.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m04.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m05.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m06.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m07.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m08.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m09.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m10.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m11.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m12.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m13.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m14.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m15.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m16.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m17.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m18.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m19.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m20.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m21.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m22.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m23.stars.txt
./new_star_report 3 mirror_geometry.3parm results/md_m24.stars.txt
./new_star_report 4 mirror_geometry.4parm results/br_m00.stars.txt
./new_star_report 4 mirror_geometry.4parm results/br_m01.stars.txt
./new_star_report 4 mirror_geometry.4parm results/br_m02.stars.txt
./new_star_report 4 mirror_geometry.4parm results/br_m03.stars.txt
./new_star_report 4 mirror_geometry.4parm results/br_m04.stars.txt
./new_star_report 4 mirror_geometry.4parm results/br_m05.stars.txt
./new_star_report 4 mirror_geometry.4parm results/br_m06.stars.txt
./new_star_report 4 mirror_geometry.4parm results/br_m07.stars.txt
./new_star_report 4 mirror_geometry.4parm results/br_m08.stars.txt
./new_star_report 4 mirror_geometry.4parm results/br_m09.stars.txt
./new_star_report 4 mirror_geometry.4parm results/br_m10.stars.txt
./new_star_report 4 mirror_geometry.4parm results/br_m11.stars.txt
./new_star_report 4 mirror_geometry.4parm results/lr_m00.stars.txt
./new_star_report 4 mirror_geometry.4parm results/lr_m01.stars.txt
./new_star_report 4 mirror_geometry.4parm results/lr_m02.stars.txt
./new_star_report 4 mirror_geometry.4parm results/lr_m03.stars.txt
./new_star_report 4 mirror_geometry.4parm results/lr_m04.stars.txt
./new_star_report 4 mirror_geometry.4parm results/lr_m05.stars.txt
./new_star_report 4 mirror_geometry.4parm results/lr_m06.stars.txt
./new_star_report 4 mirror_geometry.4parm results/lr_m07.stars.txt
./new_star_report 4 mirror_geometry.4parm results/lr_m08.stars.txt
./new_star_report 4 mirror_geometry.4parm results/lr_m09.stars.txt
./new_star_report 4 mirror_geometry.4parm results/lr_m10.stars.txt
./new_star_report 4 mirror_geometry.4parm results/lr_m11.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m01.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m02.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m03.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m04.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m05.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m06.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m07.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m08.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m09.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m10.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m11.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m12.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m13.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m14.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m15.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m16.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m17.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m18.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m19.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m20.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m21.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m22.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m23.stars.txt
./new_star_report 4 mirror_geometry.4parm results/md_m24.stars.txt
